### ISSUE TITLE
Unable to gloss on sites using HTTPS

### ISSUE THREAD

**Issue by mattq** [tealtan/gloss-server#6]
I'm unable to mark sentences on Readability or Medium, two sites that serve the articles on https://. Console throws this error: 

> The page at 'https://medium.com/innovation-thoughts/7a24fd84a49b' was loaded over HTTPS, but ran insecure content from 'http://www.glossed.it/gloss-production.js': this content should also be loaded over HTTPS.

**Comment by tealtan** [comment]
@mattq Can you explain a bit more? I was able to highlight and save a sentence from that Medium article.

**Comment by mattq** [comment]
Sorry, should have been more specific. This happened in Chrome, which apparently likes to block scripts running over HTTP when the parent page is HTTPS.

![screen shot 2014-02-11 at 11 43 46 am](https://f.cloud.github.com/assets/573182/2139185/cc3c80b8-933b-11e3-81ca-54f1ae360899.png)

**Comment by tealtan** [comment]
Ah, gotcha. Thanks!

**Comment by tealtan** [comment]
Ok, this should properly work now, upon uninstalling and reinstalling your bookmarklet.
